# Generated by Django 5.1.6 on 2026-06-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_quantity'),
        ('products', '0002_remove_product_stock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
